#!/bin/csh -f

if ( $#argv < 4 ) then
  echo "This filtering script needs a few arguments to run" 
  echo "Please specify the geodynamic model directory and names of the dvs and dvp slices, "
  echo "as well as the first and last layers"
  echo "e.g. dofilt_ESEP model names firstlay lastlay"
  echo "e.g. ./dofilt_ESEP examplemodel examplefile 1 64"
  echo "Please try again, with the right argument this time."
  exit
endif

#-- This is the working directory of tomofilt/
if ( $TOMOFILT == "" ) then
  echo "Set \"TOMOFILT\" to the directory with the model data, lib and bin dirs"
  exit
endif

echo TOMOFILT is defined to be \"$TOMOFILT\"

#-- This includes the various SP12RTS models, as well as the S20RTS/S40RTS
#-- model files such the smth and evc files
#-- These are separated into the subdirectories 
#-- subdirectories $UTILS/SP12RTS, $UTILS/S12RTS, $UTILS/S20RTS and $UTILS/S40RTS
set UTILS = $TOMOFILT/utils
echo UTILS is defined to be \"$UTILS\"

#-- binaries
set BINDIR = $TOMOFILT/bin

#-- Directory with Geodynamics simulations
set gdir = $TOMOFILT/geodyn

#-- Parameters defined here are for the geodynamic simulation
set model         = $1 
set names         = $2 
echo model directory defined to be \"$gdir/$model\"
#-- First layer below the crust
set first_layer = $3
#-- Last layer above the core
set last_layer  = $4
echo $last_layer layers in input model

#-- degree = 12 for SP12RTS
set degree = 12
echo Filtering up to degree $degree
if ($degree != 12) then
  echo Define \"degree\" to be 12
  exit
endif

#----------------------------------------------------------
#-- Symbolic links to the .evc and .smthp_21 files

echo Filtering files defined to be
#-- data weights
set wtfile = $UTILS/SP${degree}RTS/SP${degree}RTS.smthp_42
echo \"$wtfile\"
#-- eigenvector file
set evcfl  = $UTILS/SP${degree}RTS/SP${degree}RTS.evc
echo \"$evcfl\"
#-- header file
set header  = $UTILS/SP${degree}RTS/header.spt
echo \"$header\"

#-- regularization factor which depends mostly
#-- on the sampling of dVs in the simulations.
set regl = 1

#----------------------------------------------------------
#-- do_step1 = 1 --> run the projection and catting for each SPH file
set do_step1 = 1
#-- do_step1a = 1 --> project each layer into the SPH parameterisation
set do_step1a = 1
#-- do_step1b = 1 --> catting of SPH files 
set do_step1b = 1

#--------------------------------------------------------------

#-- Step 1
#-- Run the reparametrisation for both the dvs and dvp models
#-- We assume slice files for both are present in the same directory
#-- and that they have the same number of layers
if ( $do_step1 == 1 ) then
  foreach name ( ${names}.dvs ${names}.dvp )
  echo "Reparameterising file:" $name

  #-- Step 1a
  #--
  #-- Projecting the field parameters into SPH parameterisation
  #-- Do this for each layer separately
  if ( $do_step1a == 1 ) then
    #-- begin with layer "first_layer" (below the crust ...)
    @ iz = $first_layer
    while ( $iz < $last_layer )
      echo Working on layer $iz ...
      #-- make a copy
      set num = ` echo $iz | awk '{if ($1<10) print "00"$1 ; else if ($1<100) print "0"$1 ; else print $1}' `

      cat $gdir/$model/${name}.layer.${num}.dat > out

      #-- depth range
      set dep1 = `awk -v iz=$iz '{if (NR==iz) print $0}' $gdir/$model/depth_layers.dat `
      set dep2 = `awk -v iz=$iz '{if (NR==iz+1) print $0}' $gdir/$model/depth_layers.dat `
      echo Depth range = $dep1 - $dep2

      #--  number of gridpoints
      set n = `wc -l out | awk '{print $1}'`
      echo Number of gridpoints = $n

      #-- copy maps into "inpm" 
      cat out | awk '{print $1, $2, $3}' > inpm
    
      #-- make RAW file (... projection into spherical harmonics).
      #-- This is only necessary for iz="first_layer", because all the
      #-- layers have the same distribution of points on the globe
      #-- so the spherical harmonic expansion coefficients are the same for each layer.
      #-- If the layers have different distributions, you will need to run
      #-- mkexpmatxy for each layer separately.
      #-- Can be done, but let's assume here that the grids for each layer are the same ....
      echo Making RAW file ...
      if ($iz == $first_layer) then
        echo Running mkexpmatxy
        echo inpm       >  in
        echo inpm.a     >> in
        echo inpm.evc   >> in
        echo test
        echo $degree    >> in
        echo test2
        $BINDIR/mkexpmatxy  <  in
        echo test3
      endif
      echo Running invexpandxy
      echo inpm         >  in
      echo inpm.raw     >> in
      echo inpm.a       >> in
      echo inpm.evc     >> in
      echo $regl        >> in
      $BINDIR/invexpandxy   < in

      #-- Projecting this layer into the 3D SPH (s12rts/s20rts/s40rts) parameterisation
      echo Running sphexp_opendap
      echo inpm.raw     >  in
      echo $dep1        >> in
      echo $dep2        >> in
      echo inpm.$iz.sph >> in
      $BINDIR/sphexp_opendap        <  in
      @ iz++
    end
  endif

  #--------------------------------------------------------------
  #-- Step 1b
  #--
  #-- Catting each layer into a single SPH file
  if ( $do_step1b == 1 ) then
    #-- Cat SPH files
    foreach sph ( inpm.?.sph inpm.??.sph inpm.???.sph )
      set n = $sph:r:e
      if ($n == $first_layer) then
        /bin/cp $sph ll.sph
      else
        #-- ll.sph = ll.sph + $sph
        echo ll.sph       >  in
        echo $sph         >> in
        echo dummy.sph    >> in
        $BINDIR/sphadd        < in  > out_sphadd
        /bin/mv dummy.sph ll.sph
      endif
    end
    /bin/mv ll.sph inpm.SP${degree}.$name.repar.sph
    cp inpm.SP${degree}.$name.repar.sph $gdir/
    /bin/rm inpm.?.sph inpm.??.sph inpm.???.sph out_sphadd
   /bin/rm fort.103 in inpm inpm.a inpm.evc inpm.raw out tmp.evc
  endif

  #-- The file "inpm.SP${degree}.$name.repar.sph" is the geodynamics file
  #-- projected into the sp12rts parameterisation
  #-- Where $name is both $name_dvs and $name_dvp, resulting in two files.
  end
endif


